name: Test Action

inputs:
  name:
    required: true
    type: string

env:
  ENV_NAME: test

runs:
  using: composite
  steps:
    - name: Test step
      id: test
      shell: bash
      run: |
        echo "Hello, ${{ inputs.name }}! at ${{ env.ENV_NAME }}"
