name: Test Action

inputs:
  name:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Test step
      shell: bash
      run: |
        echo "Hello, ${{ inputs.name }}! at ${{ env.GLOBAL_ENV }}"
