name: Test Action

inputs:
  name:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Test step
      id: test
      shell: bash
      env:
        LOCAL_ENV: ${{ secrets.TEST_SECRET }}
      run: |
        echo "Hello, ${{ inputs.name }}! at ${{ env.GLOBAL_ENV }}"
        echo "Hello, ${{ inputs.name }}! at $LOCAL_ENV"
